name = input("Enter your name : ")
grade = input("Enter your grade : ")
number = input("Enter your number : ")
age = input("Enter your age : ")
print("--------------------------------")
print("Name :",name)
print("Grade :",grade)
print("Nunber :",number)
print("Age :",age)
